/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grade.managment;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author nazal
 */
public class GradeSystem extends javax.swing.JFrame {

    private int length = 10;
    static int pos=0;
    private String[] students = new String[length];
    private int[] mark1 = new int[length];
    private int[] mark2 = new int[length];
    /**
     * Creates new form GradeSystem
     */
    public GradeSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addStudent_btn = new javax.swing.JButton();
        addMarks_btn = new javax.swing.JButton();
        displayNames_btn = new javax.swing.JButton();
        grades_btn = new javax.swing.JButton();
        studentAvg_btn = new javax.swing.JButton();
        classAvg_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addStudent_btn.setText("Add Student");
        addStudent_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudent_btnActionPerformed(evt);
            }
        });

        addMarks_btn.setText("Add marks");
        addMarks_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarks_btnActionPerformed(evt);
            }
        });

        displayNames_btn.setText("Display Names");
        displayNames_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayNames_btnActionPerformed(evt);
            }
        });

        grades_btn.setText("Grades");
        grades_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grades_btnActionPerformed(evt);
            }
        });

        studentAvg_btn.setText("Student Avg");
        studentAvg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAvg_btnActionPerformed(evt);
            }
        });

        classAvg_btn.setText("Class Avg");
        classAvg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classAvg_btnActionPerformed(evt);
            }
        });

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addStudent_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayNames_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grades_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentAvg_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classAvg_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addMarks_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(addStudent_btn)
                        .addGap(18, 18, 18)
                        .addComponent(addMarks_btn)
                        .addGap(18, 18, 18)
                        .addComponent(displayNames_btn)
                        .addGap(18, 18, 18)
                        .addComponent(grades_btn)
                        .addGap(18, 18, 18)
                        .addComponent(studentAvg_btn)
                        .addGap(18, 18, 18)
                        .addComponent(classAvg_btn)
                        .addGap(44, 44, 44)
                        .addComponent(clear_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudent_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudent_btnActionPerformed
        // TODO add your handling code here:
        students[pos] = JOptionPane.showInputDialog(null, "Enter your name:", "Input Dialog", JOptionPane.PLAIN_MESSAGE);
        pos++;
        
    }//GEN-LAST:event_addStudent_btnActionPerformed

    private void displayNames_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayNames_btnActionPerformed
        // TODO add your handling code here:
    String studentDetails = "Name \tMark 1 \tmark 2 \n";
    
    for (int i = 0; i < pos; i++) {
        studentDetails +=  students[i] +
                         "\t  " + mark1[i] +
                         "\t  " + mark2[i] +
                         "\n";
    }
    display.setText(studentDetails);
    }//GEN-LAST:event_displayNames_btnActionPerformed

    private void addMarks_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarks_btnActionPerformed
        // TODO add your handling code here:
        boolean isPresent = false;
        String name = JOptionPane.showInputDialog(null,"Enter the name of the student","student name",JOptionPane.PLAIN_MESSAGE);
        name = name.toLowerCase();
        for(int i=0;i<pos;i++){
            if(!students[i].equalsIgnoreCase(name)){
            } else {
                isPresent = true;
                mark1[i] = Integer.parseInt(JOptionPane.showInputDialog(null,"Enter marks in subject 1 (Out of 100) ","Subject 1",JOptionPane.PLAIN_MESSAGE));
                mark2[i] = Integer.parseInt(JOptionPane.showInputDialog(null,"Enter marks in subject 2 (Out of 100)","Subject 2",JOptionPane.PLAIN_MESSAGE));
            }
        }
        if(!isPresent){
            JOptionPane.showMessageDialog(rootPane, "Name not found");
        }
    }//GEN-LAST:event_addMarks_btnActionPerformed

    private String checkGrade(int mark){
        if(mark>=90){
            return "A";
        }
        else if(mark>=80 && mark<90){
            return "B";
        }
        else if(mark>=70 && mark<80){
            return "C";
        }
        else if(mark>=60 && mark<70){
            return "D";
        }
        else{
            return "F";
        }
    }
    private void grades_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grades_btnActionPerformed
        // TODO add your handling code here:
        String details = "Name \t Grade1 \t Grade2 \n";
        for(int i=0;i<pos;i++){
            details+=students[i]+"\t  "+checkGrade(mark1[i])+"\t  "+checkGrade(mark2[i])+"\n";
        }
        display.setText(details);
    }//GEN-LAST:event_grades_btnActionPerformed
    
    private int getStudent(String name){
        for(int i=0;i<pos;i++){
            if(name.equalsIgnoreCase(students[i])){
                return i;
            }
        }
        return -1;
    }
    private void studentAvg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAvg_btnActionPerformed
        // TODO add your handling code here:
        String details = "Name \t Avg  \n";
        String name = JOptionPane.showInputDialog(null,"Enter student name ","Student",JOptionPane.PLAIN_MESSAGE);
        int index = getStudent(name);
        if(index != -1){
            double avg = (mark1[index]+mark2[index])/2;
            details+=students[index]+"\t"+avg+"\n";
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Name not found");
        }
        display.setText(details);
    }//GEN-LAST:event_studentAvg_btnActionPerformed

    private double studentAvg(int index){
        double avg = mark1[index]+mark2[index];
        return avg;
    }
    private void classAvg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classAvg_btnActionPerformed
        // TODO add your handling code here:
        String details = "Total average of the class is ";
        double avg = 0;
        for(int i=0;i<pos;i++){
            avg+=studentAvg(i);
        }
        avg = avg/pos+1;
        details+=avg/2;
        display.setText(details);
    }//GEN-LAST:event_classAvg_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        display.setText("");
    }//GEN-LAST:event_clear_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMarks_btn;
    private javax.swing.JButton addStudent_btn;
    private javax.swing.JButton classAvg_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JTextPane display;
    private javax.swing.JButton displayNames_btn;
    private javax.swing.JButton grades_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton studentAvg_btn;
    // End of variables declaration//GEN-END:variables
}
